### ISSUE TITLE
Calendar displays Spanish for non-spanish speakers

### ISSUE THREAD

**Issue by MalanB** [alexgt9/pairing-matrix#1]
Currently the date of the month is being displayed in es-US which is not understandable to Non-Spanish speakers. 
![image](https://user-images.githubusercontent.com/16334028/202184445-356d7e0d-85b1-4182-a365-1f66cc03edd4.png)

I have two suggestions
- Make it to en-US to make it consistent as other parts of the site
- Add google translate widget so that users can opt to translate in case they need it - https://developers.google.com/search/blog/2020/05/google-translates-website-translator

**Comment by alexgt9** [comment]
Fixed by #2
